# Generated by Django 3.1.13 on 2021-11-24 02:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Bucket',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
            ],
            options={
                'verbose_name_plural': 'Categories',
            },
        ),
        migrations.CreateModel(
            name='Language',
            fields=[
                ('code', models.CharField(max_length=8, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='Phenomenon',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='backend.category')),
            ],
            options={
                'verbose_name_plural': 'Phenomena',
            },
        ),
        migrations.CreateModel(
            name='Testset',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(max_length=250)),
            ],
        ),
        migrations.CreateModel(
            name='TestItem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('generation_time', models.DateField()),
                ('source_sentence', models.CharField(max_length=1000)),
                ('phenomenon', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='backend.phenomenon')),
                ('testset', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='backend.testset')),
            ],
        ),
        migrations.CreateModel(
            name='Rule',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rule_string', models.CharField(max_length=200)),
                ('prefix', models.BooleanField()),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='backend.testitem')),
            ],
        ),
        migrations.CreateModel(
            name='Langpair',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('source_language', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='source_language', to='backend.language')),
                ('target_language', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='target_language', to='backend.language')),
            ],
        ),
        migrations.AddField(
            model_name='category',
            name='langpair',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='backend.langpair'),
        ),
        migrations.CreateModel(
            name='BucketItem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('token', models.CharField(max_length=30)),
                ('bucket', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='backend.bucket')),
            ],
        ),
        migrations.CreateModel(
            name='BucketCategory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=25)),
                ('source_language', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='backend.language')),
            ],
            options={
                'verbose_name_plural': 'BucketCategories',
            },
        ),
        migrations.AddField(
            model_name='bucket',
            name='bucket_category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='backend.bucketcategory'),
        ),
    ]
