# Generated by Django 3.1.13 on 2021-11-24 00:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='bucketcategory',
            options={'verbose_name_plural': 'BucketCategories'},
        ),
        migrations.AlterModelOptions(
            name='category',
            options={'verbose_name_plural': 'Categories'},
        ),
        migrations.AlterModelOptions(
            name='phenomenon',
            options={'verbose_name_plural': 'Phenomena'},
        ),
    ]
