# Generated by Django 4.2 on 2023-04-03 23:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('evaluator', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Bucket',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='BucketItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('token', models.CharField(max_length=30)),
                ('bucket', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='generator.bucket')),
            ],
        ),
        migrations.CreateModel(
            name='BucketCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=25)),
                ('source_language', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='evaluator.language')),
            ],
            options={
                'verbose_name_plural': 'BucketCategories',
            },
        ),
        migrations.AddField(
            model_name='bucket',
            name='bucket_category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='generator.bucketcategory'),
        ),
    ]
