# Generated by Django 4.2.1 on 2023-05-31 21:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('evaluator', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=100)),
                ('last_name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254)),
                ('affiliation', models.CharField(max_length=100)),
                ('occupation', models.CharField(max_length=100)),
                ('reason', models.TextField()),
            ],
        ),
        migrations.RenameField(
            model_name='report',
            old_name='client',
            new_name='engine',
        ),
        migrations.RenameField(
            model_name='template',
            old_name='description',
            new_name='name',
        ),
        migrations.AddField(
            model_name='template',
            name='categories',
            field=models.ManyToManyField(to='evaluator.category'),
        ),
    ]
