# Generated by Django 4.2.1 on 2023-06-21 14:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('evaluator', '0002_user_rename_client_report_engine_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='User',
        ),
    ]
