# Generated by Django 4.2.5 on 2024-01-19 10:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('evaluator', '0007_alter_report_engine_alter_report_engine_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='report',
            name='comment',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
