# Generated by Django 5.0.3 on 2024-03-22 10:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('evaluator', '0008_alter_report_comment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='testitem',
            name='legacy_id',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='testitem',
            name='legacy_testpoint',
            field=models.SmallIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='testitem',
            name='legacy_version',
            field=models.SmallIntegerField(blank=True, null=True),
        ),
    ]
