# Generated by Django 5.0.3 on 2024-07-07 14:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('evaluator', '0011_alter_rule_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='translation',
            name='label',
            field=models.IntegerField(choices=[(1, 'Pass'), (2, 'Fail'), (3, 'Warning'), (4, 'Conflict')], default=3),
        ),
    ]
